version: "3.7"

services:
  web:
    image: getumbrel/tallycoin_connect:v1.0.0
    restart: on-failure
    stop_grace_period: 1m
    ports:
      # Replace <port> with the port that your app's web server
      # is listening inside the Docker container. If you need to
      # expose more ports, add them below.
      - 8123:8123
    environment:
      # Pass any environment variables to your app for configuration in the form:
      # VARIABLE_NAME: value
      #
      # Here are all the Umbrel provided variables that you can pass through to
      # your app to connect to Bitcoin Core, LND, Electrum and Tor:

      # Bitcoin Core connection details
      BTCEXP_BITCOIND_HOST: $BITCOIN_IP
      BTCEXP_BITCOIND_PORT: $BITCOIN_RPC_PORT
      BTCEXP_BITCOIND_USER: $BITCOIN_RPC_USER
      BTCEXP_BITCOIND_PASS: $BITCOIN_RPC_PASS
      
      # LND environment variables
      # $LND_IP - Local IP of LND
      # $LND_GRPC_PORT - gRPC Port of LND
      # $LND_REST_PORT - REST Port of LND

      # App specific environment variables
      TALLYCOIN_APIKEY: $TALLYCOIN_APIKEY
      TALLYCOIN_PASSWD: $TALLYCOIN_PASSWD
      LND_TLSCERT_PATH: $LND_TLSCERT_PATH
      LND_MACAROON_PATH: $LND_MACAROON_PATH
      LND_SOCKET: $LND_SOCKET


